In [32]:
import pandas as pd

movie = pd.read_csv("../../NLP_Projects/IMDB Dataset.csv")
movie.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

# min_n, max_n = 1,1

vect = CountVectorizer(max_features=100,
                        # ngram_range=(min_n,max_n)
                        )
vect.fit(movie.review)

In [ ]:
# transform the review column
X_review = vect.transform(movie.review)
type(X_review)

scipy.sparse._csr.csr_matrix

In [ ]:
X_review[:5]

<5x100 sparse matrix of type '<class 'numpy.int64'>'
	with 202 stored elements in Compressed Sparse Row format>

In [ ]:
X_df = pd.DataFrame(X_review.toarray(),columns=vect.get_feature_names_out())
X_df.head()

,about,after,all,also,an,and,any,are,as,at,...,well,were,what,when,which,who,will,with,would,you
0,1,1,1,0,1,6,0,2,4,0,...,1,0,2,0,1,2,0,5,1,3
1,1,0,2,0,0,7,0,2,0,0,...,3,0,0,0,1,0,0,3,0,1
2,0,0,0,0,0,4,0,1,0,1,...,1,0,0,1,0,0,0,2,0,0
3,0,0,3,0,0,4,0,2,2,0,...,1,0,0,1,1,0,0,3,0,2
4,2,0,2,0,0,5,0,1,1,0,...,0,0,1,0,1,0,0,1,0,0

In [ ]:
vect2 = CountVectorizer(max_df=50)
vect2.fit(movie.review)

X_review2 = vect2.transform(movie.review)

In [ ]:
# Only convert the first 5 rows to avoid MemoryError
X_df2 = pd.DataFrame(X_review2[:5].toarray(), columns=vect2.get_feature_names_out())

X_df2.head()

,00000000000,0000000000001,00000001,00001,00015,000dm,000s,001,003830,006,...,ünel,ünfaithful,üvegtigris,üzümcü,ýs,þorleifsson,þór,żmijewski,יגאל,כרמון
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

Lets learn about langdetect now.

In [ ]:
# %pip install langdetect
from langdetect import detect_langs

foreign = "De cualquier manera lograré todo lo que deseo en mi vida."
detect_langs(foreign)

[es:0.9999948659068746]

In [ ]:
nepali = "यो मन त मेरो नेपाली हो |"
detect_langs(nepali)

[ne:0.9999963279288628]