Dataset is divided into three parts.
1. Training dataset: mostly training data. 70-80% of total dataset.
2. Testing dataset: Left untouch.
3. Validation dataset: it is part of training dataset for validation purpose.

Types of Cross Validation:
- Leave one out Cross validation: In this method, we always leave 1 row of data out from whole training data for validation. if we have dataset of size 1300, where 300 is testing. 10000 is training data then, we need 1000 iterations to create our validation data. It **overfits** and very slow and tedious. No one uses it.

- Hold out Cross Validation: We use random_state to randomly select the data for validation. It can either be overfitting or underfitting.

- K-Fold Cross Validation: We divide the training data into k parts (chunks). where 1 of k chunks is validation data whereas (k-1) chunks is training data. It is very popular and very efficient. K is a hyperparameter and generate value of k is set between **5-10**. It may sound similar to LOOCV but in this we iteration till K<sup>th</sup> whereas in LOOCV we do iteration till N<sup>th</sup>. for the average of accuracy, we calculate it by average of CV1 + CV2 + ...+ CVK
still it will not work with imbalanced dataset.

- Stratified Cross Validation: In this cross validation we tend to have the data with equal or near equal no of outcomes. like if have all together 100 data in validation dataset, i tend to have 50 true, 50 false or 60 true and 40 false like that. It **works with imbalanced dataset** too and tends to fix it at some extend.

- Time Series Cross Validation: Time series data **requires sequential data based on time**. It mimics real-world scenarios by ensuring the model only learns from the past to predict the immediate future, making the evaluation more reliable for time-dependent data.

In [1]:
import pandas as pd

df = pd.read_csv("./diabetes_clean.csv")
df.head()

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [2]:
df.describe()

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [3]:
df = df.dropna().drop_duplicates()
df

,pregnancies,glucose,diastolic,triceps,insulin,bmi,dpf,age,diabetes
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
X = df.drop(labels="diabetes", axis=1)
y = df["diabetes"]

In [5]:
print(X.head())
print(y.head())

   pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age
0            6      148         72       35        0  33.6  0.627   50
1            1       85         66       29        0  26.6  0.351   31
2            8      183         64        0        0  23.3  0.672   32
3            1       89         66       23       94  28.1  0.167   21
4            0      137         40       35      168  43.1  2.288   33
0    1
1    0
2    1
3    0
4    1
Name: diabetes, dtype: int64

In [6]:
from sklearn.model_selection import train_test_split

X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print(X_train_val.shape, X_test.shape, y_train_val.shape, y_test.shape)

(614, 8) (154, 8) (614,) (154,)

In [7]:
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size=0.25, random_state=42
)
print(X_train.shape, X_val.shape, y_train.shape, y_val.shape)

(460, 8) (154, 8) (460,) (154,)

In [8]:
print(df.shape)
print(X.shape, y.shape)

(768, 9)
(768, 8) (768,)